[project]
name = "cli-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.11",
    "modal>=0.73.107",
    "numpy>=2.2.3",
    "torch>=2.6.0",
]
